"""Component IDs kept in one discoverable place."""

APP_ROOT = "app-root"
URL = "app-url"
SYMBOL_INPUT = "symbol-input"
LOAD_BUTTON = "load-button"
REFRESH_BUTTON = "refresh-button"
INTERVAL_SELECT = "interval-select"
THEME_BUTTON = "theme-button"
CHART = "price-chart"
CHART_TITLE = "chart-title"
STATUS = "data-status"
DETAILS = "chart-details"
QUICK_SYMBOL_TYPE = "quick-symbol"
SCANNER_STATUS = "scanner-status"
ALERT_POLL = "alert-poll"
ALERT_COUNT = "alert-count"
ALERT_LIST = "alert-list"
ALERT_ACK_ALL = "alert-ack-all"
ALERT_ACK_TYPE = "alert-ack"
ALERT_MUTE_TYPE = "alert-mute"
